app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  link-check-properties:
    link-check-interval: 10m
  database-access-type: jdbc

spring:
  application:
    name: scrapper
  liquibase:
    change-log: liquibase/master.xml
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "info, health, prometheus"
      path-mapping:
        prometheus: metrics
  retrofit:
    applicationProperty: application=${spring.application.name}
    add-application-as-prefix: true
  server:
    port: 8081
  enable:
    http.server.requests: true
